### PR TITLE
Fix Issue #76 - dropping un-clustered PSNUs in clustered OUs.

### PR DESCRIPTION
**Pull request by jacksonsj**

### CODE REVIEW

**Comment by jacksonsj** [comment]
Morning. The cases are:

**Military**
If _Military, then keep values as received from Disagg Tool

**Clusters**
- If has match in Pcts (has history) --> use Pcts to map cluster to underlying PSNUs & multiply value by psnuPct
- If does not have match in Pcts --> join with clusterAvgs to map to underlying PSNUs & multiply value by avg

**Un-clustered PSNU**
Keep values as received from Disagg Tool

**Comment by jason-p-pickering** [comment]
OK. I think I get it. 
Let me have a look at it. You get some sleep.

**Comment by jason-p-pickering** [comment]
So, running this code with Namibia's data, I am getting duplicates. At this point there should be no duplicates in the data. 

```
> sum(duplicated(d$data[,1:5]))
 [1] 2306
--
```

**Comment by jason-p-pickering** [comment]
As an example
```
    
    foo<-d$data %>% 
      dplyr::select(-value) %>% 
      dplyr::group_by(dataelement,period,orgunit,categoryoptioncombo,attributeoptioncombo) %>%
      dplyr::mutate(count=n()) %>%
      dplyr::filter(count > 1) %>%
      dplyr::ungroup() %>%
      dplyr::inner_join(d$data, by=c("dataelement","period","orgunit","categoryoptioncombo","attributeoptioncombo")) %>%
      dplyr::arrange(dataelement,period,orgunit,categoryoptioncombo,attributeoptioncombo)
```

image

**Comment by jason-p-pickering** [comment]
@jacksonsj I have redone this with #79 as a merge into this branch.

**Pull request merged**
